name: firstworkflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: salutation
        run: echo "hi guy we are learning github actions"
      - name: install apache
        run: sudo apt-get install apache2 -y
        
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: update system
        run: sudo apt-get update -y
        
      - name: install java
        run: sudo apt install default-jdk
    
     
